version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: "trust"
  web:
    build: main
    volumes:
      - .:/main
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - main/.env